version: "3"
services:

  langfuse-server:
    image: langfuse/langfuse:2.95
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:axlrator!1@91.99.20.220:5432/axlrlangfuse
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://91.99.20.220:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    networks:
      - alfred_network

  rag_server:
    image: rag_server # 빌드된 이미지 이름
    build: .
    container_name: rag_server
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - ../rag_server:/app/rag_server
      - ../rag_data:/app/rag_data
    networks:
      - alfred_network
    stdin_open: true # -i 옵션 (인터랙티브 모드)
    tty: true # -t 옵션 (터미널 할당)

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # 보안 비활성화
    networks:
      - alfred_network # 네트워크 연결 추가

networks:
  alfred_network:
    driver: bridge

volumes:
  database_data:
    driver: local
