# 기본 이미지
FROM alpine:3.20

# 시스템 의존성 설치
RUN apk update && \
    apk add --no-cache \
    python3 \
    py3-pip \
    py3-virtualenv \
    nodejs \
    npm \
    postgresql-dev \
    gcc \
    musl-dev \
    libffi-dev \
    python3-dev \
    swig \
    libxml2-dev \
    libxslt-dev \
    make \
    git

# python 및 pip에 대한 심볼릭 링크 생성
RUN ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

# 작업 디렉토리 설정
WORKDIR /app/rag_server

# 현재 디렉토리의 모든 파일을 컨테이너의 /app/rag_server 디렉토리에 복사
COPY . /app/rag_server

# 가상 환경 생성 (Python 3을 명시적으로 사용)
RUN python3 -m venv venv

# requirements.txt 파일 복사 및 가상 환경에서 파이썬 의존성 설치
COPY requirements.txt /app/rag_server/
RUN /app/rag_server/venv/bin/python3 -m pip install --no-cache-dir -r /app/rag_server/requirements.txt

# 가상 환경에서 앱 실행
# CMD ["/app/rag_server/venv/bin/python3", "-m", "app.server"]