"""empty message

Revision ID: 093fc9c75396
Revises: 109a6480234a
Create Date: 2024-09-13 08:28:28.995803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093fc9c75396'
down_revision: Union[str, None] = '109a6480234a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faiss_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=512), nullable=True),
    sa.Column('index_desc', sa.Text(), nullable=True),
    sa.Column('index_file_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faiss_info_id'), 'faiss_info', ['id'], unique=False)
    op.add_column('model_info', sa.Column('model_version', sa.String(length=256), nullable=True))
    op.alter_column('model_info', 'model_type',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.drop_index('ix_model_info_desc', table_name='model_info')
    op.drop_index('ix_model_info_model_name', table_name='model_info')
    op.add_column('org_resrc', sa.Column('faiss_info_id', sa.Integer(), nullable=True))
    op.alter_column('org_resrc', 'resrc_type',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(length=4),
               existing_nullable=True)
    op.drop_index('ix_org_resrc_last_modified_time', table_name='org_resrc')
    op.drop_index('ix_org_resrc_resrc_desc', table_name='org_resrc')
    op.drop_index('ix_org_resrc_resrc_name', table_name='org_resrc')
    op.drop_index('ix_org_resrc_resrc_path', table_name='org_resrc')
    op.create_foreign_key(None, 'org_resrc', 'faiss_info', ['faiss_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_resrc', type_='foreignkey')
    op.create_index('ix_org_resrc_resrc_path', 'org_resrc', ['resrc_path'], unique=False)
    op.create_index('ix_org_resrc_resrc_name', 'org_resrc', ['resrc_name'], unique=False)
    op.create_index('ix_org_resrc_resrc_desc', 'org_resrc', ['resrc_desc'], unique=False)
    op.create_index('ix_org_resrc_last_modified_time', 'org_resrc', ['last_modified_time'], unique=False)
    op.alter_column('org_resrc', 'resrc_type',
               existing_type=sa.String(length=4),
               type_=sa.CHAR(length=4),
               existing_nullable=True)
    op.drop_column('org_resrc', 'faiss_info_id')
    op.create_index('ix_model_info_model_name', 'model_info', ['model_name'], unique=False)
    op.create_index('ix_model_info_desc', 'model_info', ['desc'], unique=False)
    op.alter_column('model_info', 'model_type',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True)
    op.drop_column('model_info', 'model_version')
    op.drop_index(op.f('ix_faiss_info_id'), table_name='faiss_info')
    op.drop_table('faiss_info')
    # ### end Alembic commands ###
