"""empty message

Revision ID: 0c080d81403e
Revises: 62c2e5a3423c
Create Date: 2024-09-19 10:30:51.453337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c080d81403e'
down_revision: Union[str, None] = '62c2e5a3423c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('model_name', sa.String(length=512), nullable=True, comment='모델명'),
    sa.Column('desc', sa.Text(), nullable=True, comment='모델 설명'),
    sa.Column('model_type', sa.String(length=2), nullable=True, comment='모델 유형'),
    sa.Column('model_version', sa.String(length=256), nullable=True, comment='모델 버전'),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True, comment='최종수정시간'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='생성시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_info_created_at'), 'model_info', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_info_id'), 'model_info', ['id'], unique=False)
    op.create_index(op.f('ix_model_info_model_type'), 'model_info', ['model_type'], unique=False)
    op.create_index(op.f('ix_model_info_modified_at'), 'model_info', ['modified_at'], unique=False)
    op.create_table('org_resrc',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('resrc_name', sa.String(), nullable=True, comment='리소스명'),
    sa.Column('resrc_type', sa.String(length=4), nullable=True, comment='리소스 유형'),
    sa.Column('resrc_path', sa.Text(), nullable=True, comment='리소스 위치'),
    sa.Column('resrc_desc', sa.Text(), nullable=True, comment='리소스 상세'),
    sa.Column('is_vector', sa.Boolean(), nullable=True, comment='벡터화 여부'),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True, comment='최종수정시간'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='생성시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_resrc_created_at'), 'org_resrc', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_resrc_id'), 'org_resrc', ['id'], unique=False)
    op.create_index(op.f('ix_org_resrc_modified_at'), 'org_resrc', ['modified_at'], unique=False)
    op.create_index(op.f('ix_org_resrc_resrc_type'), 'org_resrc', ['resrc_type'], unique=False)
    op.create_table('chunked_data',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('seq', sa.Integer(), nullable=True, comment='순번'),
    sa.Column('org_resrc_id', sa.Integer(), nullable=True, comment='OrgRSrc FK'),
    sa.Column('data_name', sa.String(), nullable=True, comment='데이터명'),
    sa.Column('data_type', sa.Text(), nullable=True, comment='데이터 유형'),
    sa.Column('content', sa.Text(), nullable=True, comment='콘텐츠'),
    sa.Column('document_metadata', sa.JSON(), nullable=True, comment='문서의 메타데이터'),
    sa.Column('vector_index', sa.BigInteger(), nullable=True, comment='벡터 인덱스값'),
    sa.Column('index_file_path', sa.Text(), nullable=True, comment='인덱스 파일 경로'),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True, comment='최종수정시간'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='생성시간'),
    sa.ForeignKeyConstraint(['org_resrc_id'], ['org_resrc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunked_data_created_at'), 'chunked_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_chunked_data_id'), 'chunked_data', ['id'], unique=False)
    op.create_index(op.f('ix_chunked_data_modified_at'), 'chunked_data', ['modified_at'], unique=False)
    op.create_index(op.f('ix_chunked_data_seq'), 'chunked_data', ['seq'], unique=False)
    op.create_index(op.f('ix_chunked_data_vector_index'), 'chunked_data', ['vector_index'], unique=False)
    op.create_table('org_resrc_code',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('org_resrc_id', sa.Integer(), nullable=True, comment='OrgRSrc FK'),
    sa.Column('project_info', sa.Text(), nullable=True, comment='프로젝트 정보'),
    sa.Column('package_name', sa.Text(), nullable=True, comment='패키지명'),
    sa.Column('class_type', sa.Text(), nullable=True, comment='클래스타입'),
    sa.Column('class_name', sa.String(), nullable=True, comment='클래스명'),
    sa.Column('class_extends', sa.Text(), nullable=True, comment='상속자'),
    sa.Column('class_implements', sa.Text(), nullable=True, comment='구현자'),
    sa.Column('class_imports', sa.Text(), nullable=True, comment='임포트'),
    sa.Column('class_attributes', sa.Text(), nullable=True, comment='어트리뷰트'),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True, comment='최종수정시간'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='생성시간'),
    sa.ForeignKeyConstraint(['org_resrc_id'], ['org_resrc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_resrc_code_created_at'), 'org_resrc_code', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_resrc_code_id'), 'org_resrc_code', ['id'], unique=False)
    op.create_index(op.f('ix_org_resrc_code_modified_at'), 'org_resrc_code', ['modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_resrc_code_modified_at'), table_name='org_resrc_code')
    op.drop_index(op.f('ix_org_resrc_code_id'), table_name='org_resrc_code')
    op.drop_index(op.f('ix_org_resrc_code_created_at'), table_name='org_resrc_code')
    op.drop_table('org_resrc_code')
    op.drop_index(op.f('ix_chunked_data_vector_index'), table_name='chunked_data')
    op.drop_index(op.f('ix_chunked_data_seq'), table_name='chunked_data')
    op.drop_index(op.f('ix_chunked_data_modified_at'), table_name='chunked_data')
    op.drop_index(op.f('ix_chunked_data_id'), table_name='chunked_data')
    op.drop_index(op.f('ix_chunked_data_created_at'), table_name='chunked_data')
    op.drop_table('chunked_data')
    op.drop_index(op.f('ix_org_resrc_resrc_type'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_modified_at'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_id'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_created_at'), table_name='org_resrc')
    op.drop_table('org_resrc')
    op.drop_index(op.f('ix_model_info_modified_at'), table_name='model_info')
    op.drop_index(op.f('ix_model_info_model_type'), table_name='model_info')
    op.drop_index(op.f('ix_model_info_id'), table_name='model_info')
    op.drop_index(op.f('ix_model_info_created_at'), table_name='model_info')
    op.drop_table('model_info')
    # ### end Alembic commands ###
