"""empty message

Revision ID: 109a6480234a
Revises: 1ba5372313b9
Create Date: 2024-09-13 05:42:44.350161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109a6480234a'
down_revision: Union[str, None] = '1ba5372313b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_resrc_data', 'vector_index',
               existing_type=sa.TEXT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_org_resrc_data_vector_index'), 'org_resrc_data', ['vector_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_resrc_data_vector_index'), table_name='org_resrc_data')
    op.alter_column('org_resrc_data', 'vector_index',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
