"""empty message

Revision ID: 1ba5372313b9
Revises: 6b9e3bcc133e
Create Date: 2024-09-13 05:25:20.261229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba5372313b9'
down_revision: Union[str, None] = '6b9e3bcc133e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_resrc_data', sa.Column('vector_index', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_resrc_data', 'vector_index')
    # ### end Alembic commands ###
