"""empty message

Revision ID: 5a9c26abe2d9
Revises: 0c080d81403e
Create Date: 2024-09-19 10:48:23.969921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9c26abe2d9'
down_revision: Union[str, None] = '0c080d81403e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faiss_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('index_name', sa.String(), nullable=True, comment='인덱스명'),
    sa.Column('index_desc', sa.Text(), nullable=True, comment='인덱스 설명'),
    sa.Column('index_file_path', sa.Text(), nullable=True, comment='인덱스 파일 경로'),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True, comment='최종수정시간'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='생성시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faiss_info_created_at'), 'faiss_info', ['created_at'], unique=False)
    op.create_index(op.f('ix_faiss_info_id'), 'faiss_info', ['id'], unique=False)
    op.create_index(op.f('ix_faiss_info_modified_at'), 'faiss_info', ['modified_at'], unique=False)
    op.add_column('chunked_data', sa.Column('faiss_info_id', sa.Integer(), nullable=True, comment='FaissInfo FK'))
    op.create_foreign_key(None, 'chunked_data', 'faiss_info', ['faiss_info_id'], ['id'])
    op.drop_column('chunked_data', 'index_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunked_data', sa.Column('index_file_path', sa.TEXT(), autoincrement=False, nullable=True, comment='인덱스 파일 경로'))
    op.drop_constraint(None, 'chunked_data', type_='foreignkey')
    op.drop_column('chunked_data', 'faiss_info_id')
    op.drop_index(op.f('ix_faiss_info_modified_at'), table_name='faiss_info')
    op.drop_index(op.f('ix_faiss_info_id'), table_name='faiss_info')
    op.drop_index(op.f('ix_faiss_info_created_at'), table_name='faiss_info')
    op.drop_table('faiss_info')
    # ### end Alembic commands ###
