"""empty message

Revision ID: 62c2e5a3423c
Revises: f8cc7d2cb647
Create Date: 2024-09-15 11:40:04.990059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c2e5a3423c'
down_revision: Union[str, None] = 'f8cc7d2cb647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docstore_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['org_resrc_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docstore_index_id'), 'docstore_index', ['id'], unique=False)
    op.create_index(op.f('ix_docstore_index_index'), 'docstore_index', ['index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docstore_index_index'), table_name='docstore_index')
    op.drop_index(op.f('ix_docstore_index_id'), table_name='docstore_index')
    op.drop_table('docstore_index')
    # ### end Alembic commands ###
