"""empty message

Revision ID: 6fc4465bdd4f
Revises: 82d527765a79
Create Date: 2024-12-08 15:51:51.994554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc4465bdd4f'
down_revision: Union[str, None] = '82d527765a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsrc_table',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('table_name', sa.String(), nullable=True, comment='테이블명'),
    sa.Column('table_desc', sa.Text(), nullable=True, comment='테이블 설명'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='생성시간'),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True, comment='최종수정시간'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'),
    sa.Column('modified_by', sa.String(length=50), nullable=True, comment='최종수정자'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsrc_table_created_at'), 'rsrc_table', ['created_at'], unique=False)
    op.create_index(op.f('ix_rsrc_table_created_by'), 'rsrc_table', ['created_by'], unique=False)
    op.create_index(op.f('ix_rsrc_table_id'), 'rsrc_table', ['id'], unique=False)
    op.create_index(op.f('ix_rsrc_table_modified_at'), 'rsrc_table', ['modified_at'], unique=False)
    op.create_index(op.f('ix_rsrc_table_modified_by'), 'rsrc_table', ['modified_by'], unique=False)
    op.create_table('rsrc_table_column',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('column_name', sa.String(), nullable=True, comment='컬럼명'),
    sa.Column('column_korean_name', sa.String(), nullable=True, comment='컬럼 한글명'),
    sa.Column('column_type', sa.String(), nullable=True, comment='컬럼 타입'),
    sa.Column('column_desc', sa.Text(), nullable=True, comment='컬럼 설명'),
    sa.Column('rsrc_table_id', sa.Integer(), nullable=True, comment='rsrc_table FK'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='생성시간'),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True, comment='최종수정시간'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'),
    sa.Column('modified_by', sa.String(length=50), nullable=True, comment='최종수정자'),
    sa.ForeignKeyConstraint(['rsrc_table_id'], ['rsrc_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsrc_table_column_created_at'), 'rsrc_table_column', ['created_at'], unique=False)
    op.create_index(op.f('ix_rsrc_table_column_created_by'), 'rsrc_table_column', ['created_by'], unique=False)
    op.create_index(op.f('ix_rsrc_table_column_id'), 'rsrc_table_column', ['id'], unique=False)
    op.create_index(op.f('ix_rsrc_table_column_modified_at'), 'rsrc_table_column', ['modified_at'], unique=False)
    op.create_index(op.f('ix_rsrc_table_column_modified_by'), 'rsrc_table_column', ['modified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rsrc_table_column_modified_by'), table_name='rsrc_table_column')
    op.drop_index(op.f('ix_rsrc_table_column_modified_at'), table_name='rsrc_table_column')
    op.drop_index(op.f('ix_rsrc_table_column_id'), table_name='rsrc_table_column')
    op.drop_index(op.f('ix_rsrc_table_column_created_by'), table_name='rsrc_table_column')
    op.drop_index(op.f('ix_rsrc_table_column_created_at'), table_name='rsrc_table_column')
    op.drop_table('rsrc_table_column')
    op.drop_index(op.f('ix_rsrc_table_modified_by'), table_name='rsrc_table')
    op.drop_index(op.f('ix_rsrc_table_modified_at'), table_name='rsrc_table')
    op.drop_index(op.f('ix_rsrc_table_id'), table_name='rsrc_table')
    op.drop_index(op.f('ix_rsrc_table_created_by'), table_name='rsrc_table')
    op.drop_index(op.f('ix_rsrc_table_created_at'), table_name='rsrc_table')
    op.drop_table('rsrc_table')
    # ### end Alembic commands ###
