"""empty message

Revision ID: 82d527765a79
Revises: c38fd85c7605
Create Date: 2024-10-04 07:48:13.176185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d527765a79'
down_revision: Union[str, None] = 'c38fd85c7605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunked_data', sa.Column('context_chunk', sa.Text(), nullable=True, comment='컨텍스트 청크'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunked_data', 'context_chunk')
    # ### end Alembic commands ###
