"""empty message

Revision ID: b4c7771e4a6f
Revises: 
Create Date: 2024-09-12 06:46:58.315022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c7771e4a6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('model_type', sa.CHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_info_desc'), 'model_info', ['desc'], unique=False)
    op.create_index(op.f('ix_model_info_id'), 'model_info', ['id'], unique=False)
    op.create_index(op.f('ix_model_info_model_name'), 'model_info', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_info_model_type'), 'model_info', ['model_type'], unique=False)
    op.create_table('org_resrc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resrc_name', sa.String(), nullable=True),
    sa.Column('resrc_type', sa.CHAR(length=4), nullable=True),
    sa.Column('resrc_path', sa.Text(), nullable=True),
    sa.Column('resrc_desc', sa.Text(), nullable=True),
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_resrc_id'), 'org_resrc', ['id'], unique=False)
    op.create_index(op.f('ix_org_resrc_last_modified_time'), 'org_resrc', ['last_modified_time'], unique=False)
    op.create_index(op.f('ix_org_resrc_resrc_desc'), 'org_resrc', ['resrc_desc'], unique=False)
    op.create_index(op.f('ix_org_resrc_resrc_name'), 'org_resrc', ['resrc_name'], unique=False)
    op.create_index(op.f('ix_org_resrc_resrc_path'), 'org_resrc', ['resrc_path'], unique=False)
    op.create_index(op.f('ix_org_resrc_resrc_type'), 'org_resrc', ['resrc_type'], unique=False)
    op.create_table('org_resrc_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_resrc_id', sa.Integer(), nullable=True),
    sa.Column('project_info', sa.Text(), nullable=True),
    sa.Column('package_name', sa.Text(), nullable=True),
    sa.Column('class_type', sa.Text(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('class_extends', sa.Text(), nullable=True),
    sa.Column('class_implements', sa.Text(), nullable=True),
    sa.Column('class_imports', sa.Text(), nullable=True),
    sa.Column('class_attributes', sa.Text(), nullable=True),
    sa.Column('class_methods_cnt', sa.Integer(), nullable=True),
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_resrc_id'], ['org_resrc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_resrc_code_id'), 'org_resrc_code', ['id'], unique=False)
    op.create_index(op.f('ix_org_resrc_code_last_modified_time'), 'org_resrc_code', ['last_modified_time'], unique=False)
    op.create_table('org_resrc_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('org_resrc_id', sa.Integer(), nullable=True),
    sa.Column('data_name', sa.String(), nullable=True),
    sa.Column('data_type', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_resrc_id'], ['org_resrc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_resrc_data_create_at'), 'org_resrc_data', ['create_at'], unique=False)
    op.create_index(op.f('ix_org_resrc_data_id'), 'org_resrc_data', ['id'], unique=False)
    op.create_index(op.f('ix_org_resrc_data_seq'), 'org_resrc_data', ['seq'], unique=False)
    op.create_table('org_resrc_data_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_resrc_data_id', sa.Integer(), nullable=True),
    sa.Column('return_type', sa.Text(), nullable=True),
    sa.Column('parameter', sa.Text(), nullable=True),
    sa.Column('create_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_resrc_data_id'], ['org_resrc_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_resrc_data_code_create_at'), 'org_resrc_data_code', ['create_at'], unique=False)
    op.create_index(op.f('ix_org_resrc_data_code_id'), 'org_resrc_data_code', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_resrc_data_code_id'), table_name='org_resrc_data_code')
    op.drop_index(op.f('ix_org_resrc_data_code_create_at'), table_name='org_resrc_data_code')
    op.drop_table('org_resrc_data_code')
    op.drop_index(op.f('ix_org_resrc_data_seq'), table_name='org_resrc_data')
    op.drop_index(op.f('ix_org_resrc_data_id'), table_name='org_resrc_data')
    op.drop_index(op.f('ix_org_resrc_data_create_at'), table_name='org_resrc_data')
    op.drop_table('org_resrc_data')
    op.drop_index(op.f('ix_org_resrc_code_last_modified_time'), table_name='org_resrc_code')
    op.drop_index(op.f('ix_org_resrc_code_id'), table_name='org_resrc_code')
    op.drop_table('org_resrc_code')
    op.drop_index(op.f('ix_org_resrc_resrc_type'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_resrc_path'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_resrc_name'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_resrc_desc'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_last_modified_time'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_id'), table_name='org_resrc')
    op.drop_table('org_resrc')
    op.drop_index(op.f('ix_model_info_model_type'), table_name='model_info')
    op.drop_index(op.f('ix_model_info_model_name'), table_name='model_info')
    op.drop_index(op.f('ix_model_info_id'), table_name='model_info')
    op.drop_index(op.f('ix_model_info_desc'), table_name='model_info')
    op.drop_table('model_info')
    # ### end Alembic commands ###
