"""empty message

Revision ID: c38fd85c7605
Revises: 5a9c26abe2d9
Create Date: 2024-09-27 05:09:47.398061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38fd85c7605'
down_revision: Union[str, None] = '5a9c26abe2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunked_data', sa.Column('modified_by', sa.String(length=50), nullable=True, comment='최종수정자'))
    op.add_column('chunked_data', sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'))
    op.create_index(op.f('ix_chunked_data_created_by'), 'chunked_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_chunked_data_modified_by'), 'chunked_data', ['modified_by'], unique=False)
    op.add_column('faiss_info', sa.Column('modified_by', sa.String(length=50), nullable=True, comment='최종수정자'))
    op.add_column('faiss_info', sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'))
    op.create_index(op.f('ix_faiss_info_created_by'), 'faiss_info', ['created_by'], unique=False)
    op.create_index(op.f('ix_faiss_info_modified_by'), 'faiss_info', ['modified_by'], unique=False)
    op.add_column('model_info', sa.Column('modified_by', sa.String(length=50), nullable=True, comment='최종수정자'))
    op.add_column('model_info', sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'))
    op.create_index(op.f('ix_model_info_created_by'), 'model_info', ['created_by'], unique=False)
    op.create_index(op.f('ix_model_info_modified_by'), 'model_info', ['modified_by'], unique=False)
    op.add_column('org_resrc', sa.Column('modified_by', sa.String(length=50), nullable=True, comment='최종수정자'))
    op.add_column('org_resrc', sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'))
    op.create_index(op.f('ix_org_resrc_created_by'), 'org_resrc', ['created_by'], unique=False)
    op.create_index(op.f('ix_org_resrc_modified_by'), 'org_resrc', ['modified_by'], unique=False)
    op.add_column('org_resrc_code', sa.Column('modified_by', sa.String(length=50), nullable=True, comment='최종수정자'))
    op.add_column('org_resrc_code', sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'))
    op.create_index(op.f('ix_org_resrc_code_created_by'), 'org_resrc_code', ['created_by'], unique=False)
    op.create_index(op.f('ix_org_resrc_code_modified_by'), 'org_resrc_code', ['modified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_resrc_code_modified_by'), table_name='org_resrc_code')
    op.drop_index(op.f('ix_org_resrc_code_created_by'), table_name='org_resrc_code')
    op.drop_column('org_resrc_code', 'created_by')
    op.drop_column('org_resrc_code', 'modified_by')
    op.drop_index(op.f('ix_org_resrc_modified_by'), table_name='org_resrc')
    op.drop_index(op.f('ix_org_resrc_created_by'), table_name='org_resrc')
    op.drop_column('org_resrc', 'created_by')
    op.drop_column('org_resrc', 'modified_by')
    op.drop_index(op.f('ix_model_info_modified_by'), table_name='model_info')
    op.drop_index(op.f('ix_model_info_created_by'), table_name='model_info')
    op.drop_column('model_info', 'created_by')
    op.drop_column('model_info', 'modified_by')
    op.drop_index(op.f('ix_faiss_info_modified_by'), table_name='faiss_info')
    op.drop_index(op.f('ix_faiss_info_created_by'), table_name='faiss_info')
    op.drop_column('faiss_info', 'created_by')
    op.drop_column('faiss_info', 'modified_by')
    op.drop_index(op.f('ix_chunked_data_modified_by'), table_name='chunked_data')
    op.drop_index(op.f('ix_chunked_data_created_by'), table_name='chunked_data')
    op.drop_column('chunked_data', 'created_by')
    op.drop_column('chunked_data', 'modified_by')
    # ### end Alembic commands ###
