"""empty message

Revision ID: f8cc7d2cb647
Revises: 6f4bbe71720f
Create Date: 2024-09-13 12:18:54.160827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cc7d2cb647'
down_revision: Union[str, None] = '6f4bbe71720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_resrc', sa.Column('is_vector', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_resrc', 'is_vector')
    # ### end Alembic commands ###
